### ISSUE TITLE
Multiple paging instances on single page causes next / prev to not function correctly

### ISSUE THREAD

**Issue by amartinezatcpo** [neighbordog/jquery-paginate#1]
When placing 2 instances on the same page, the prev and next do not behave as expected (paging to the next/prev page) but instead jump to the last / first page when clicked.

**Comment by neighbordog** [comment]
Should be resolved with https://github.com/neighbordog/jquery-paginate/commit/4ed91007ac9bbdc4c446bd5896edf08df3eed1a9
